# Generated by Django 5.2.4 on 2025-07-28 04:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['time_stamp', 'order']},
        ),
        migrations.AlterModelOptions(
            name='workday',
            options={'ordering': ['date_stamp']},
        ),
        migrations.AlterField(
            model_name='action',
            name='time_stamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workday',
            name='date_stamp',
            field=models.DateField(),
        ),
    ]
