# Generated by Django 5.2.4 on 2025-07-29 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_action_options_alter_workday_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['time_stamp', 'order'], 'verbose_name': 'Действие', 'verbose_name_plural': 'Действия'},
        ),
        migrations.AlterModelOptions(
            name='workday',
            options={'ordering': ['date_stamp'], 'verbose_name': 'Рабочий день', 'verbose_name_plural': 'Рабочие дни'},
        ),
        migrations.AlterUniqueTogether(
            name='action',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='action',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='action',
            name='status_gate',
            field=models.CharField(choices=[('EG', 'Вход'), ('OG', 'Выход')], max_length=2, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='action',
            name='time_stamp',
            field=models.DateTimeField(verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='action',
            name='workday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='accounts.workday', verbose_name='Рабочий день'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='date_stamp',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='type',
            field=models.CharField(choices=[('ND', 'Обычный день'), ('WD', 'Выходной'), ('HD', 'Праздник'), ('VL', 'Отпуск'), ('SMD', 'Короткий день')], default='ND', max_length=3, verbose_name='Тип дня'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workdays', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
