# Generated by Django 5.2.4 on 2025-08-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_action_options_alter_workday_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='entry_type',
            field=models.CharField(choices=[('default', 'Обычное время'), ('mk', 'МК-время')], default='default', max_length=10),
        ),
    ]
