# Generated by Django 5.2.4 on 2025-08-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_action_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='entry_type',
            field=models.CharField(choices=[('default', 'Обычное время'), ('mk', 'МК-время')], default='default', max_length=10, verbose_name='МК/неМК'),
        ),
    ]
