# Generated by Django 5.2.4 on 2025-09-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_action_entry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='is_calculated',
            field=models.BooleanField(default=False),
        ),
    ]
