# Generated by Django 5.2.4 on 2025-09-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_action_is_calculated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('full_day', 'Полный день'), ('shortened', 'Сокращённый'), ('student', 'Студент')], default='full_day', max_length=15, verbose_name='Тип учетной записи'),
        ),
    ]
