# Generated by Django 5.2.4 on 2025-11-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_workday_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='type',
            field=models.CharField(choices=[('ND', 'Рабочий день'), ('WD', 'Выходной'), ('HD', 'Праздник'), ('VL', 'Отпуск'), ('SMD', 'Короткий день'), ('ED', 'пустой день')], default='ND', max_length=3, verbose_name='Тип дня'),
        ),
    ]
