# Generated by Django 5.2.4 on 2026-01-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_workday_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='type',
            field=models.CharField(choices=[('ND', 'Рабочий день'), ('WD', 'Выходной'), ('HD', 'Праздник'), ('VL', 'Отпуск'), ('SMD', 'Короткий день'), ('ED', 'пустой день'), ('OT', 'Отгул'), ('MK', 'Местная командировка'), ('KMD', 'Командироватка')], default='ND', max_length=3, verbose_name='Тип дня'),
        ),
    ]
