# Generated by Django 5.2.4 on 2026-08-11 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_workday_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='type',
            field=models.CharField(choices=[('ND', 'Рабочий день'), ('WD', 'Выходной'), ('HD', 'Праздник'), ('VL', 'Отпуск'), ('SMD', 'Короткий день'), ('ED', 'пустой день'), ('OT', 'Отгул'), ('MK', 'Местная командировка'), ('KMD', 'Командировка')], default='ND', max_length=3, verbose_name='Тип дня'),
        ),
        migrations.CreateModel(
            name='MonthTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_year', models.IntegerField(verbose_name='Год списания')),
                ('from_month', models.IntegerField(verbose_name='Месяц списания')),
                ('to_year', models.IntegerField(verbose_name='Год зачисления')),
                ('to_month', models.IntegerField(verbose_name='Месяц зачисления')),
                ('amount_seconds', models.IntegerField(verbose_name='Секунды переноса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Перенос времени между месяцами',
                'verbose_name_plural': 'Переносы времени между месяцами',
            },
        ),
    ]
