# Generated by Django 5.2.15 on 2026-08-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_workday_type_monthtransfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата рождения')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'День рождения',
                'verbose_name_plural': 'Дни рождения',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('day_type', models.CharField(choices=[('HD', 'Праздник'), ('SMD', 'Короткий день')], default='HD', max_length=5, verbose_name='Тип дня')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Праздник / Сокращённый день',
                'verbose_name_plural': 'Праздники и сокращённые дни',
                'ordering': ['date'],
            },
        ),
    ]
