# Generated by Django 5.2.4 on 2026-08-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_department_user_is_department_head_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='type',
            field=models.CharField(choices=[('ND', 'Рабочий день'), ('WD', 'Выходной'), ('HD', 'Праздник'), ('VL', 'Отпуск'), ('SMD', 'Короткий день'), ('ED', 'пустой день'), ('OT', 'Отгул'), ('MK', 'Больничный'), ('KMD', 'Командировка')], default='ND', max_length=3, verbose_name='Тип дня'),
        ),
    ]
