# Generated by Django 5.2.4 on 2026-08-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_workday_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tracker',
            field=models.CharField(default='Сегодня', max_length=100, verbose_name='Текст трекера'),
        ),
    ]
