# Generated by Django 5.2.4 on 2026-08-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_tracker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthtransfer',
            options={'verbose_name': 'Перенос / Добавление времени', 'verbose_name_plural': 'Переносы и добавления времени'},
        ),
        migrations.AddField(
            model_name='monthtransfer',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Описание / Комментарий'),
        ),
        migrations.AlterField(
            model_name='monthtransfer',
            name='from_month',
            field=models.IntegerField(blank=True, null=True, verbose_name='Месяц списания'),
        ),
        migrations.AlterField(
            model_name='monthtransfer',
            name='from_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год списания'),
        ),
    ]
