# Generated by Django 5.2.15 on 2026-09-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_monthtransfer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodayPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=100, verbose_name='Фраза')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Фраза «Сегодня»',
                'verbose_name_plural': 'Фразы «Сегодня»',
            },
        ),
    ]
