# Generated by Django 5.2.15 on 2026-09-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_task_status_taskcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_read_by_assignee',
            field=models.BooleanField(default=False, verbose_name='Прочитано исполнителем'),
        ),
        migrations.AddField(
            model_name='task',
            name='status_changed_for_head',
            field=models.BooleanField(default=False, verbose_name='Статус изменён для начальника'),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
