# Generated by Django 5.2.15 on 2026-09-27 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_task_is_read_by_assignee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_change_detail',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Детали последнего изменения'),
        ),
    ]
