# Generated by Django 5.2.15 on 2026-09-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_task_last_change_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('assigned', 'Назначено'), ('pending_review', 'На проверке'), ('rework', 'На доработке'), ('done', 'Выполнено')], default='assigned', max_length=20, verbose_name='Статус'),
        ),
    ]
