# Generated by Django 5.2.15 on 2026-09-28 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_user_is_administrator'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='Код приоритета (0-4)')),
                ('name', models.CharField(max_length=100, verbose_name='Название приоритета')),
                ('color_code', models.CharField(default='#ef4444', max_length=30, verbose_name='Цвет (HEX / CSS)')),
            ],
            options={
                'verbose_name': 'Приоритет задачи',
                'verbose_name_plural': 'Приоритеты задач',
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['due_date', 'priority__code', '-created_at'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AddField(
            model_name='task',
            name='archive_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Ссылка на архив'),
        ),
        migrations.AddField(
            model_name='task',
            name='co_assignees',
            field=models.ManyToManyField(blank=True, related_name='co_assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Дополнительные исполнители'),
        ),
        migrations.AddField(
            model_name='task',
            name='schedule_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Номер графика'),
        ),
        migrations.AddField(
            model_name='task',
            name='schedule_type',
            field=models.CharField(choices=[('off_schedule', 'Не по графику'), ('on_schedule', 'По графику')], default='off_schedule', max_length=20, verbose_name='График'),
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=100, verbose_name='Тип действия')),
                ('description', models.TextField(verbose_name='Подробное описание изменения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто совершил действие')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='accounts.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'История задачи',
                'verbose_name_plural': 'История задач',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.taskpriority', verbose_name='Приоритет'),
        ),
        migrations.CreateModel(
            name='TaskCoAssigneeApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Согласовано')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время согласования')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_assignee_approvals', to='accounts.task', verbose_name='Задача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Доп. исполнитель')),
            ],
            options={
                'verbose_name': 'Согласование ДИ',
                'verbose_name_plural': 'Согласования ДИ',
                'unique_together': {('task', 'user')},
            },
        ),
    ]
