# Generated by Django 5.2.15 on 2026-10-02 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_taskpriority_alter_task_options_task_archive_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskcomment',
            options={'ordering': ['created_at', 'id'], 'verbose_name': 'Комментарий к задаче', 'verbose_name_plural': 'Комментарии к задачам'},
        ),
        migrations.AlterModelOptions(
            name='taskhistory',
            options={'ordering': ['created_at'], 'verbose_name': 'История задачи', 'verbose_name_plural': 'История задач'},
        ),
        migrations.AddField(
            model_name='task',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='accounts.department', verbose_name='Отдел'),
        ),
    ]
