# Generated by Django 5.2.15 on 2026-10-02 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_department_options_alter_department_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название темы')),
            ],
            options={
                'verbose_name': 'Тема задачи',
                'verbose_name_plural': 'Темы задач',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='accounts.tasktopic', verbose_name='Тема задачи'),
        ),
    ]
