# Generated by Django 5.2.15 on 2026-10-04 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_tasktopic_task_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('FS', 'Окончание → Начало (FS)'), ('SS', 'Начало → Начало (SS)'), ('FF', 'Окончание → Окончание (FF)'), ('SF', 'Начало → Окончание (SF)')], default='FS', max_length=2, verbose_name='Тип связи')),
                ('lag_lead_days', models.IntegerField(default=0, verbose_name='Сдвиг (дней)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking_dependencies', to='accounts.task', verbose_name='Связанная задача (предшественник)')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='accounts.task', verbose_name='Текущая задача')),
            ],
            options={
                'verbose_name': 'Хронологическая зависимость',
                'verbose_name_plural': 'Хронологические зависимости',
                'unique_together': {('task', 'depends_on')},
            },
        ),
    ]
