# Generated by Django 5.2.15 on 2026-10-06 21:30

from django.db import migrations, models


def populate_default_colors(apps, schema_editor):
    ChatColor = apps.get_model('accounts', 'ChatColor')
    default_colors = [
        ('#2563eb', 'Синий (Классический)', 10),
        ('#4f46e5', 'Индиго', 20),
        ('#7c3aed', 'Фиолетовый', 30),
        ('#db2777', 'Розовый', 40),
        ('#059669', 'Изумрудный', 50),
        ('#0d9488', 'Морская волна', 60),
        ('#0891b2', 'Бирюзовый', 70),
        ('#d97706', 'Янтарный', 80),
        ('#ea580c', 'Оранжевый', 90),
        ('#e11d48', 'Коралловый', 100),
        ('#65a30d', 'Лайм', 110),
        ('#475569', 'Сланцевый', 120),
    ]
    for hex_code, name, order in default_colors:
        ChatColor.objects.get_or_create(
            color_hex=hex_code,
            defaults={'name': name, 'order': order, 'is_active': True}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_user_chat_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название цвета')),
                ('color_hex', models.CharField(help_text='Например: #3b82f6 или выберите из палитры', max_length=20, unique=True, verbose_name='HEX-код цвета')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Цвет чата',
                'verbose_name_plural': 'Цвета чата',
                'ordering': ['order', 'name', 'id'],
            },
        ),
        migrations.RenameIndex(
            model_name='taskusernotification',
            new_name='accounts_ta_user_id_a2a410_idx',
            old_name='accounts_ta_user_id_44f1cf_idx',
        ),
        migrations.RunPython(populate_default_colors, migrations.RunPython.noop),
    ]

