# Generated by Django 5.2.15 on 2026-10-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_chatcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chat_color',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Цвет сообщений в чате'),
        ),
    ]
